export const LANDING = '/'
export const HOME = '/'
export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const FORGOT_PASSWORD = '/forgot-password'
export const SERVICES = '/services'
export const MAP = '/map'
export const SCANNERS = '/scanners'
export const ATTRIBUTION = '/attribution'
export const LISTINGS = '/listings'
export const listingPath = (id) => `/listing/${id}`
export const LISTING_CREATE = '/createlisting'
export const JOBS = '/jobs'
export const MESSAGES = '/messages'
export const conversationPath = (id) => `/conversation/${id}`
export const ACCOUNT = '/account'
export const CHANGE_PASSWORD = '/changepassword'
export const ADMIN = '/admin'
